apiVersion: v1
kind: Service
metadata:
  name: nginx-service
annotations:
  argocd.argoproj.io/sync-options: Prune=false
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
